answers = [
    "asteroid supernova atom gravity orbit",
    "orbit electron electron photon universe",
    "black hole particle light electron density",
    "comet neutron meteor gravity light",
    "gravity atom black hole meteor speed",
    "mass molecule planet black hole supernova",
    "force light black hole planet particle",
    "photon sun supernova nebula mass",
    "nucleus wave electron atom quasar",
    "sun light force star mass",
    "supernova speed nucleus particle energy",
    "photon planet black hole star photon",
    "electron density molecule black hole neutron",
    "density black hole planet gravity orbit",
    "meteor quasar nebula black hole asteroid",
    "molecule nucleus comet nucleus mass",
    "moon meteor molecule electron density",
    "quasar sun orbit proton mass",
    "quasar nucleus supernova asteroid moon",
    "proton electron supernova proton gravity",
    "moon galaxy photon star mass",
    "energy gravity universe asteroid wave",
    "comet orbit photon wave star",
    "comet asteroid quasar sun quasar",
    "light atom energy gravity atom",
    "electron gravity molecule wave particle",
    "star comet orbit light quasar",
    "density particle moon speed energy",
    "energy gravity universe particle molecule",
    "mass gravity neutron nebula electron"
]
