runtime: python39
entrypoint: gunicorn -b :$PORT jennie.wsgi

service_account: jennie@jennie-1720624972853.iam.gserviceaccount.com

handlers:
- url: /static
  static_dir: staticfiles

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "jennie.settings"
  # Add any other environment variables you need, for example:
  # SECRET_KEY: "your-secret-key"
  # DATABASE_URL: "your-database-url"
