# Generated by Django 5.0.6 on 2024-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_interview_interviewsession_interviewblock_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
