# Generated by Django 5.0.6 on 2024-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_interview_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationblock',
            name='block_type',
            field=models.CharField(choices=[('QA', 'Question-Answer'), ('Code_Block', 'Code_Block'), ('YT', 'YouTube Video'), ('LINK', 'Link'), ('MOCK', 'MOCK')], max_length=10),
        ),
    ]
