# Generated by Django 5.0.6 on 2024-07-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_preparationblock_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('link', models.URLField()),
                ('preparation_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_2', to='base.preparationmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('embed_url', models.URLField()),
                ('preparation_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_3', to='base.preparationmaterial')),
            ],
        ),
    ]
