# Generated by Django 5.0.6 on 2024-07-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_googlesearchresult_youtubelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('preparation_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='base.preparationmaterial')),
            ],
        ),
    ]
