# Generated by Django 5.0.6 on 2024-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_preparationblock_block_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='my_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesearchresult',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preparationblock',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preparationblock',
            name='my_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
