# Generated by Django 5.0.6 on 2024-07-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_codingquestion_attempted_codingquestion_my_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewblock',
            name='my_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewblock',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewblock',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewblock',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewblock',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InterviewCodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('my_answer', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0)),
                ('attempted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.interviewsession')),
            ],
        ),
    ]
