# Generated by Django 5.0.6 on 2024-07-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_interviewblock_my_answer_interviewblock_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcodingquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icoding_questions', to='base.interviewsession'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iblocks', to='base.interview'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
