# Generated by Django 5.0.6 on 2024-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
