# Generated by Django 5.0.6 on 2024-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_interviewsession_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
