# Generated by Django 4.2 on 2024-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_interviewsession_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
