# Generated by Django 5.0.7 on 2024-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_interviewsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=1000),
        ),
    ]
