# Generated by Django 5.0.7 on 2024-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='csessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tjobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usessions',
            field=models.IntegerField(default=0),
        ),
    ]
