# Generated by Django 5.0.7 on 2024-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_customuser_csessions_customuser_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preparationmaterial',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
