# Generated by Django 5.0.7 on 2024-08-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_asisstant'),
    ]

    operations = [
        migrations.AddField(
            model_name='asisstant',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
