# Generated by Django 5.0.7 on 2024-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_asisstant_last_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='asisstant',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
