# Generated by Django 5.0.7 on 2024-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_asisstant_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
