# Generated by Django 5.0.7 on 2024-08-22 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_code_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationmaterial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
