# Generated by Django 5.0.7 on 2024-10-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_preparationmaterial_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
