# Generated by Django 4.2.15 on 2024-11-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_customuser_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
