# Generated by Django 4.2.15 on 2024-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_customuser_google_calendar_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_Calendar',
            field=models.BooleanField(default=False),
        ),
    ]
